### ISSUE TITLE
potential typo in dataObserver

### ISSUE THREAD

**Issue by andrewmtoy** [offirgolan/ember-cli-nvd3#2]
Hi @offirgolan, is there a typo on the following line?
https://github.com/offirgolan/ember-cli-nvd3/blob/master/addon/components/nvd3-chart.js#L27

Should 'data' and 'data.[]' be replaced with 'datum' and 'datum.[]'?

To get the chart to observe my data changes I have to declare a component like this, which feels a bit redundant. 

``` html
{{nvd3-chart type='lineChart' data=chartSeriesArray datum=chartSeriesArray}}
```

Thanks!
Andrew

**Comment by offirgolan** [comment]
Yeah you're totally right! Thanks for the catch. I'm out of town until
Monday so I'll issue a release as soon as I can!

On Saturday, September 26, 2015, Andrew Toy notifications@github.com
wrote:

> Hi @offirgolan https://github.com/offirgolan, is there a typo on the
> following line?
> 
> https://github.com/offirgolan/ember-cli-nvd3/blob/master/addon/components/nvd3-chart.js#L27
> 
> Should 'data' and 'data.[]' be replaced with 'datum' and 'datum.[]'?
> 
> To get the chart to observe my data changes I have to declare a component
> like this, which feels a bit redundant.
> 
> {{nvd3-chart type='lineChart' data=chartSeriesArray datum=chartSeriesArray}}
> 
> Thanks!
> Andrew
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/offirgolan/ember-cli-nvd3/issues/2.

## 

Thanks,
Offir Golan

**Comment by offirgolan** [comment]
@andrewmtoy please upgrade to v0.0.4

**Comment by andrewmtoy** [comment]
awesome! thanks for the quick response.
