### ISSUE TITLE
Can't figure out how to format datum

### ISSUE THREAD

**Issue by ghost** [offirgolan/ember-cli-nvd3#4]
I've tried looking through the nvd3 docs to figure out how to format the data array, but whatever I try I can't get it working.

What I've found in the nvd3 docs is just a basic array like 

```
datum: [
        {
            "key":    "Series 1",
            "values": [
                [ 1, 70 ], [ 2, 73 ], [ 3, 66 ]

            ]
        }
    ]
```

But I just get an empty chart when I try pass that to the datum property with a bunch of errors from d3.js like

```
Error: Invalid value for <path> attribute transform="translate(NaN,NaN)"
Error: Invalid value for <path> attribute d="MZ"
etc?
```

What am I doing wrong?

**Comment by ghost** [comment]
Also, do you have an example on how to convert an Ember Data model into this format?

**Comment by offirgolan** [comment]
What type of chart are you attempting to create? Can you post some more code so I can attempt to debug this?

**Comment by offirgolan** [comment]
> Also, do you have an example on how to convert an Ember Data model into this format?

I dont think there is really the best way to convert a model to the format you need. You will have to write up the conversion on your own since nvd3 only accepts plain JS objects and arrays.

**Comment by ghost** [comment]
Hey sorry for not adding code with the post.

Just trying to create a Line Chart, I've tried it with dates etc as well but figured plain numbers would be easier to use to get a test chart up.

```
--template.js
{{nvd3-chart type="lineChart" datum=datum options=options beforeSetup=beforeSetup}}
```

```
--controller.js
export default Ember.Controller.extend({

    options: {
        chart:   {
            height: 500,
            color:  [ "#FF0000" ]
        }
    },

    beforeSetup(svgContainer /*, chart*/) {
        svgContainer.attr({
            height: 500
        });
    },

    datum: [
        {
            "key":    "Series 1",
            "values": [
                [ 1, 70 ], [ 2, 73 ], [ 3, 66 ]

            ]
        }
    ]

});
```

Errors:

```
Error: Invalid value for <path> attribute transform="translate(NaN,NaN)"attrFunction @ d3.js:669(anonymous function) @ d3.js:961d3_selection_each @ d3.js:967d3_selectionPrototype.each @ d3.js:960d3_selectionPrototype.attr @ d3.js:651(anonymous function) @ nv.d3.js:11199(anonymous function) @ d3.js:961d3_selection_each @ d3.js:967d3_selectionPrototype.each @ d3.js:960chart @ nv.d3.js:10879d3_selectionPrototype.call @ d3.js:974(anonymous function) @ nv.d3.js:5910(anonymous function) @ d3.js:961d3_selection_each @ d3.js:967d3_selectionPrototype.each @ d3.js:960chart @ nv.d3.js:5880d3_selectionPrototype.call @ d3.js:974(anonymous function) @ nv.d3.js:6240(anonymous function) @ d3.js:961d3_selection_each @ d3.js:967d3_selectionPrototype.each @ d3.js:960chart @ nv.d3.js:6131d3_selectionPrototype.call @ d3.js:974(anonymous function) @ nvd3-chart.js:68renderLoop @ nv.d3.js:94

3d3.js:669 Error: Invalid value for <path> attribute d="MZ"attrFunction @ d3.js:669(anonymous function) @ d3.js:961d3_selection_each @ d3.js:967d3_selectionPrototype.each @ d3.js:960d3_selectionPrototype.attr @ d3.js:651updateInteractiveLayer @ nv.d3.js:11028

3d3.js:669 Error: Invalid value for <circle> attribute cx="NaN"attrFunction @ d3.js:669(anonymous function) @ d3.js:961d3_selection_each @ d3.js:967d3_selectionPrototype.each @ d3.js:960d3_selectionPrototype.attr @ d3.js:651updateInteractiveLayer @ nv.d3.js:11056

3d3.js:669 Error: Invalid value for <circle> attribute cy="NaN"attrFunction @ d3.js:669(anonymous function) @ d3.js:961d3_selection_each @ d3.js:967d3_selectionPrototype.each @ d3.js:960d3_selectionPrototype.attr @ d3.js:651updateInteractiveLayer @ nv.d3.js:11057
```

Screenshot
![image](https://cloud.githubusercontent.com/assets/9647970/12705857/f18aba0a-c8c3-11e5-9317-a83adc137afd.png)

**Comment by offirgolan** [comment]
Thanks! I think the only thing I see wrong is how you define your values. They need to be a set of objects with { x, y } values.

Try the following: 

``` js
datum: [
        {
            "key":    "Series 1",
            "values": [
                { x: 1,  y: 70 }, { x: 2, y: 73 }, { x: 3,  y: 66 }
            ]
        }
    ]
```

For more details, check out the [lineChart source](https://github.com/nvd3-community/nvd3/blob/gh-pages/examples/lineChart.html)

**Comment by ghost** [comment]
Awesome that fixed it!
I reckon that would be a great addition to the readme examples on this package, as the examples I found on the main nvd3 website seemed to use a flat array as per my error?

Thanks again

**Comment by offirgolan** [comment]
Glad that worked :smile_cat: 

The documentation on the nvd3 main page is pretty outdated and that's why I linked to the [NVD3 Community docs](https://nvd3-community.github.io/nvd3/) in the readme which has updated examples, source code, and detailed docs for each graph type and more.

**Comment by jakemoves** [comment]
Hey @offirgolan, I am trying a simple pie chart using this data (found in the NVD3 community docs example:
`[
        { key: 'Shortlisted', y: 5 },
        { key: 'Rejected', y: 429 }
]`

I get an error: `data.map is not a function`...posting here instead of opening a new issue in case it's a data format issue?

**Comment by offirgolan** [comment]
@jakemoves can you post a code snippet?

**Comment by jakemoves** [comment]
Derp. Stupid error. Glad I didn't make a new issue!

**Comment by jakemoves** [comment]
Actually, I am consistently having trouble replicating the examples on the community page. Setting a 'value' format (as they do on i.e. multiBarChart) never works. I have to use 'x' and 'y'. Just in case anyone else runs into this...

**Comment by offirgolan** [comment]
@jakemoves thats really weird. Does it spit out any errors or it just ignores `value`?
