### ISSUE TITLE
Cleaning chart on willDestroyElement may be required

### ISSUE THREAD

**Issue by riklaunim** [offirgolan/ember-cli-nvd3#6]
I'm making some statistics in ember with ember-cli-nvd3 and some other charts and there is a specific bug that shows up when I resize the browser and go back and forth between routes. Canvas based Chart.js trowed an error then, and nvd3 also:

```
14d3.js:663 Error: <g> attribute transform: Expected number, "translate(NaN,5)".
```

For charts.js solution was to remove the chart on willDestroyElement (a.k.a. normal cleanup). For nvd3 similar thing happened for Angular2: http://stackoverflow.com/questions/36977176/browser-errors-on-size-change-when-ng2-nvd3-chart-is-out-of-view

**Comment by offirgolan** [comment]
@riklaunim I just published `v0.1.1` to npm with a fix for this issue. Let me know if it still persists.

**Comment by riklaunim** [comment]
Will check it tomorrow, thanks :)

**Comment by riklaunim** [comment]
Looks like fixed, the error does not show up.

**Comment by offirgolan** [comment]
👍 Awesome! Thanks for bringing this to my attention 😺
